# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-27 08:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avate', models.ImageField(default='user/icon/default.jpg', upload_to='user/icon', verbose_name='头像')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('consume', models.IntegerField(default=0, verbose_name='消费金额')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否为管理员用户')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'shop_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img', models.ImageField(upload_to='banner/img', verbose_name='轮播图表')),
                ('title', models.CharField(max_length=64, verbose_name='轮播图标题')),
            ],
            options={
                'verbose_name_plural': '轮播图表',
                'db_table': 'shop_banner',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=16, verbose_name='分类名')),
                ('cate_self', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate_son', to='api.Category', verbose_name='二级分类')),
            ],
            options={
                'verbose_name_plural': '商品分类表',
                'db_table': 'shop_cate',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_avate', models.CharField(max_length=128, verbose_name='评论人头像')),
                ('user_name', models.CharField(max_length=20, verbose_name='评论人昵称')),
                ('grade', models.IntegerField(verbose_name='商品评价分数')),
                ('context', models.CharField(max_length=128, verbose_name='评论内容')),
                ('comment_self', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.Comment', verbose_name='追评')),
            ],
            options={
                'verbose_name_plural': '评论表',
                'db_table': 'shop_comment',
            },
        ),
        migrations.CreateModel(
            name='Comment_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img', models.ImageField(upload_to='comment/img', verbose_name='图片路径')),
                ('title', models.CharField(max_length=32, verbose_name='图片标题')),
                ('comment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='com_img', to='api.Comment', verbose_name='评论图片')),
            ],
            options={
                'verbose_name_plural': '评论图片表',
                'db_table': 'shop_comment_img',
            },
        ),
        migrations.CreateModel(
            name='Good_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品原价')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品现价')),
                ('parameter', models.CharField(max_length=255, verbose_name='商品参数')),
                ('quota', models.IntegerField(default=0, verbose_name='限购数量')),
            ],
            options={
                'verbose_name_plural': '商品详情表',
                'db_table': 'shop_good_detail',
            },
        ),
        migrations.CreateModel(
            name='Good_icon_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img', models.ImageField(upload_to='good/icon/', verbose_name='图片路径')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='图片标题')),
                ('good_detail', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='icon_img', to='api.Good_detail', verbose_name='商品详情图片')),
            ],
            options={
                'verbose_name_plural': '商品详情图片表',
                'db_table': 'shop_icon_img',
            },
        ),
        migrations.CreateModel(
            name='Good_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('img', models.ImageField(upload_to='good/img', verbose_name='图片路径')),
                ('title', models.CharField(max_length=32, null=True, verbose_name='图片标题')),
            ],
            options={
                'verbose_name_plural': '商品图片表',
                'db_table': 'shop_img',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('start_time', models.DateTimeField(null=True, verbose_name='商品秒杀结束时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='商品秒杀结束时间')),
                ('is_seckill', models.BooleanField(default=False, verbose_name='是否为秒杀商品')),
                ('is_fresh', models.BooleanField(default=False, verbose_name='是否是生鲜商品')),
                ('fraction', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='商品评分')),
                ('info', models.TextField(verbose_name='商品介绍')),
                ('command_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('icon', models.ImageField(upload_to='good/img', verbose_name='商品图片')),
                ('cate', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='good', to='api.Category', verbose_name='商品分类')),
            ],
            options={
                'verbose_name_plural': '商品表',
                'db_table': 'shop_goods',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_id', models.CharField(max_length=32, verbose_name='订单号')),
                ('order_title', models.CharField(max_length=32, verbose_name='订单标题')),
                ('serial_number', models.CharField(max_length=32, null=True, verbose_name='流水号')),
                ('order_status', models.IntegerField(choices=[(0, '待付款'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已评价'), (5, '退款中'), (6, '已退款'), (7, '已取消')], default=0, verbose_name='订单状态')),
                ('pay_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='支付金额')),
                ('pay_type', models.IntegerField(choices=[(1, '支付宝'), (2, '微信')], default=1, verbose_name='支付方式')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('deliver_time', models.DateTimeField(null=True, verbose_name='发货时间')),
                ('confirm_receipt_time', models.DateTimeField(null=True, verbose_name='确认收货时间')),
                ('freight', models.DecimalField(choices=[(8, '韵达快递'), (10, '圆通快递'), (20, '顺丰快递')], decimal_places=2, max_digits=8, verbose_name='运费')),
                ('good_maney', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品金额')),
                ('order_remarks', models.CharField(max_length=120, null=True, verbose_name='备注')),
                ('logistics_number', models.CharField(default='73124161428372', max_length=20, verbose_name='物流单号')),
                ('order_user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='下单用户')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='Order_son',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good_name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('good_cate_name', models.CharField(max_length=16, verbose_name='商品分类')),
                ('good_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品单价')),
                ('good_number', models.IntegerField(verbose_name='商品数量')),
                ('count_maney', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品小计')),
                ('good', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_son', to='api.Good_detail', verbose_name='关联的商品')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_son', to='api.Order', verbose_name='链接的订单')),
            ],
            options={
                'verbose_name_plural': '订单子表',
                'db_table': 'shop_order_son',
            },
        ),
        migrations.CreateModel(
            name='Receiv_addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('consignee', models.CharField(max_length=16, verbose_name='收货人')),
                ('province', models.CharField(max_length=16, verbose_name='省')),
                ('city', models.CharField(max_length=16, verbose_name='市')),
                ('area', models.CharField(max_length=16, verbose_name='区/县')),
                ('detail_addr', models.CharField(max_length=128, verbose_name='详细地址')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='receiv_addr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '收货地址表',
                'db_table': 'shop_receiv_addr',
            },
        ),
        migrations.CreateModel(
            name='Return_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('return_money', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='退款金额')),
                ('return_msg', models.CharField(max_length=120, verbose_name='退款原因')),
                ('return_number', models.CharField(max_length=20, verbose_name='退款编号')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='return_good', to='api.Order', verbose_name='退货订单')),
            ],
            options={
                'verbose_name_plural': '退款退货表',
                'db_table': 'shop_return_goods',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock', models.IntegerField(verbose_name='库存数')),
                ('sold', models.IntegerField(verbose_name='已售数')),
                ('good_detail', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.Good_detail', verbose_name='商品id')),
            ],
            options={
                'verbose_name_plural': '库存表',
                'db_table': 'shop_stock',
            },
        ),
        migrations.CreateModel(
            name='Top_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('good', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='api.Goods', verbose_name='链接的商品')),
            ],
            options={
                'verbose_name_plural': '置顶商品',
                'db_table': 'shop_top_good',
            },
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], default=3, verbose_name='性别')),
                ('province', models.CharField(max_length=16, verbose_name='省')),
                ('city', models.CharField(max_length=16, verbose_name='市')),
                ('area', models.CharField(max_length=16, verbose_name='区/县')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
            ],
            options={
                'verbose_name_plural': '用户详情表',
                'db_table': 'shop_user_detail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='receiv_addr',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.Receiv_addr', verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='good_img',
            name='good',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='api.Goods', verbose_name='商品展示图片'),
        ),
        migrations.AddField(
            model_name='good_detail',
            name='good',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='api.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api.Goods', verbose_name='评论的商品'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='banner',
            name='good',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='api.Goods', verbose_name='链接的商品'),
        ),
    ]
